  securityContext:
    worker:
      capabilities:
        drop:
{{- range .Values.tap.securityContext.worker.capabilities.drop }}
          - {{ . }}
{{- end }}
        add:
{{- range .Values.tap.securityContext.worker.capabilities.add }}
          - {{ . }}
{{- end }}
    hub:
      capabilities:
        drop:
  {{- range .Values.tap.securityContext.capabilities.hub.drop }}
          - {{ . }}
  {{- end }}
        add:
  {{- range .Values.tap.securityContext.capabilities.hub.add }}
          - {{ . }}
  {{- end }}
    front:
      capabilities:
        drop:
  {{- range .Values.tap.securityContext.capabilities.front.drop }}
          - {{ . }}
  {{- end }}
        add:
  {{- range .Values.tap.securityContext.capabilities.front.add }}
          - {{ . }}
  {{- end }}
    hub:
      capabilities:
        drop:
{{- range .Values.tap.securityContext.hub.capabilities.drop }}
          - {{ . }}
{{- end }}
        add:
{{- range .Values.tap.securityContext.hub.capabilities.add }}
          - {{ . }}
{{- end }}
    front:
      capabilities:
        drop:
{{- range .Values.tap.securityContext.front.capabilities.drop }}
          - {{ . }}
{{- end }}
        add:
{{- range .Values.tap.securityContext.front.capabilities.add }}
          - {{ . }}
{{- end }}
